//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace datos.seguridad
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class pubsEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new pubsEntities object using the connection string found in the 'pubsEntities' section of the application configuration file.
        /// </summary>
        public pubsEntities() : base("name=pubsEntities", "pubsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new pubsEntities object.
        /// </summary>
        public pubsEntities(string connectionString) : base(connectionString, "pubsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new pubsEntities object.
        /// </summary>
        public pubsEntities(EntityConnection connection) : base(connection, "pubsEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<pub_info> pub_info
        {
            get
            {
                if ((_pub_info == null))
                {
                    _pub_info = base.CreateObjectSet<pub_info>("pub_info");
                }
                return _pub_info;
            }
        }
        private ObjectSet<pub_info> _pub_info;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the pub_info EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTopub_info(pub_info pub_info)
        {
            base.AddObject("pub_info", pub_info);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="pubsModel", Name="pub_info")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class pub_info : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new pub_info object.
        /// </summary>
        /// <param name="pub_id">Initial value of the pub_id property.</param>
        public static pub_info Createpub_info(global::System.String pub_id)
        {
            pub_info pub_info = new pub_info();
            pub_info.pub_id = pub_id;
            return pub_info;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String pub_id
        {
            get
            {
                return _pub_id;
            }
            set
            {
                if (_pub_id != value)
                {
                    Onpub_idChanging(value);
                    ReportPropertyChanging("pub_id");
                    _pub_id = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("pub_id");
                    Onpub_idChanged();
                }
            }
        }
        private global::System.String _pub_id;
        partial void Onpub_idChanging(global::System.String value);
        partial void Onpub_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] logo
        {
            get
            {
                return StructuralObject.GetValidValue(_logo);
            }
            set
            {
                OnlogoChanging(value);
                ReportPropertyChanging("logo");
                _logo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("logo");
                OnlogoChanged();
            }
        }
        private global::System.Byte[] _logo;
        partial void OnlogoChanging(global::System.Byte[] value);
        partial void OnlogoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String pr_info
        {
            get
            {
                return _pr_info;
            }
            set
            {
                Onpr_infoChanging(value);
                ReportPropertyChanging("pr_info");
                _pr_info = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("pr_info");
                Onpr_infoChanged();
            }
        }
        private global::System.String _pr_info;
        partial void Onpr_infoChanging(global::System.String value);
        partial void Onpr_infoChanged();

        #endregion
    
    }

    #endregion
    
}
