//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("SeguridadModel", "FK__persona__genero__0CBAE877", "genero", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(datos.seguridad.genero), "persona", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(datos.seguridad.persona), true)]

#endregion

namespace datos.seguridad
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class SeguridadEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new SeguridadEntities object using the connection string found in the 'SeguridadEntities' section of the application configuration file.
        /// </summary>
        public SeguridadEntities() : base("name=SeguridadEntities", "SeguridadEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SeguridadEntities object.
        /// </summary>
        public SeguridadEntities(string connectionString) : base(connectionString, "SeguridadEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SeguridadEntities object.
        /// </summary>
        public SeguridadEntities(EntityConnection connection) : base(connection, "SeguridadEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<genero> genero
        {
            get
            {
                if ((_genero == null))
                {
                    _genero = base.CreateObjectSet<genero>("genero");
                }
                return _genero;
            }
        }
        private ObjectSet<genero> _genero;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<persona> persona
        {
            get
            {
                if ((_persona == null))
                {
                    _persona = base.CreateObjectSet<persona>("persona");
                }
                return _persona;
            }
        }
        private ObjectSet<persona> _persona;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the genero EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTogenero(genero genero)
        {
            base.AddObject("genero", genero);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the persona EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTopersona(persona persona)
        {
            base.AddObject("persona", persona);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SeguridadModel", Name="genero")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class genero : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new genero object.
        /// </summary>
        /// <param name="codigo">Initial value of the codigo property.</param>
        public static genero Creategenero(global::System.Int32 codigo)
        {
            genero genero = new genero();
            genero.codigo = codigo;
            return genero;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 codigo
        {
            get
            {
                return _codigo;
            }
            set
            {
                if (_codigo != value)
                {
                    OncodigoChanging(value);
                    ReportPropertyChanging("codigo");
                    _codigo = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("codigo");
                    OncodigoChanged();
                }
            }
        }
        private global::System.Int32 _codigo;
        partial void OncodigoChanging(global::System.Int32 value);
        partial void OncodigoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SeguridadModel", "FK__persona__genero__0CBAE877", "persona")]
        public EntityCollection<persona> persona
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<persona>("SeguridadModel.FK__persona__genero__0CBAE877", "persona");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<persona>("SeguridadModel.FK__persona__genero__0CBAE877", "persona", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SeguridadModel", Name="persona")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class persona : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new persona object.
        /// </summary>
        /// <param name="codigo">Initial value of the codigo property.</param>
        /// <param name="nombre">Initial value of the nombre property.</param>
        /// <param name="apellido">Initial value of the apellido property.</param>
        public static persona Createpersona(global::System.String codigo, global::System.String nombre, global::System.String apellido)
        {
            persona persona = new persona();
            persona.codigo = codigo;
            persona.nombre = nombre;
            persona.apellido = apellido;
            return persona;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String codigo
        {
            get
            {
                return _codigo;
            }
            set
            {
                if (_codigo != value)
                {
                    OncodigoChanging(value);
                    ReportPropertyChanging("codigo");
                    _codigo = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("codigo");
                    OncodigoChanged();
                }
            }
        }
        private global::System.String _codigo;
        partial void OncodigoChanging(global::System.String value);
        partial void OncodigoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nombre
        {
            get
            {
                return _nombre;
            }
            set
            {
                OnnombreChanging(value);
                ReportPropertyChanging("nombre");
                _nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("nombre");
                OnnombreChanged();
            }
        }
        private global::System.String _nombre;
        partial void OnnombreChanging(global::System.String value);
        partial void OnnombreChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String apellido
        {
            get
            {
                return _apellido;
            }
            set
            {
                OnapellidoChanging(value);
                ReportPropertyChanging("apellido");
                _apellido = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("apellido");
                OnapellidoChanged();
            }
        }
        private global::System.String _apellido;
        partial void OnapellidoChanging(global::System.String value);
        partial void OnapellidoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> genero
        {
            get
            {
                return _genero;
            }
            set
            {
                OngeneroChanging(value);
                ReportPropertyChanging("genero");
                _genero = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("genero");
                OngeneroChanged();
            }
        }
        private Nullable<global::System.Int32> _genero;
        partial void OngeneroChanging(Nullable<global::System.Int32> value);
        partial void OngeneroChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> fechaNacimiento
        {
            get
            {
                return _fechaNacimiento;
            }
            set
            {
                OnfechaNacimientoChanging(value);
                ReportPropertyChanging("fechaNacimiento");
                _fechaNacimiento = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("fechaNacimiento");
                OnfechaNacimientoChanged();
            }
        }
        private Nullable<global::System.DateTime> _fechaNacimiento;
        partial void OnfechaNacimientoChanging(Nullable<global::System.DateTime> value);
        partial void OnfechaNacimientoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String telefono
        {
            get
            {
                return _telefono;
            }
            set
            {
                OntelefonoChanging(value);
                ReportPropertyChanging("telefono");
                _telefono = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("telefono");
                OntelefonoChanged();
            }
        }
        private global::System.String _telefono;
        partial void OntelefonoChanging(global::System.String value);
        partial void OntelefonoChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SeguridadModel", "FK__persona__genero__0CBAE877", "genero")]
        public genero genero1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<genero>("SeguridadModel.FK__persona__genero__0CBAE877", "genero").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<genero>("SeguridadModel.FK__persona__genero__0CBAE877", "genero").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<genero> genero1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<genero>("SeguridadModel.FK__persona__genero__0CBAE877", "genero");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<genero>("SeguridadModel.FK__persona__genero__0CBAE877", "genero", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
